-- DDL Script was generated by Orange for ORACLE
-- using session 'TSQL@NGMS1' on '2015/01/06 14:24:53'.

CREATE OR REPLACE package pinetri
is
    --package내부에서는 object선언이 불가능?
--    type t_tf_row as object (id number, gen_dt date, logrds number);
    type t_tf_row is record (id number, gen_dt timestamp, logrds number, exec number, ats number, apco number, undo_rec number, event varchar2(255));
    type t_tf_tab is table of t_tf_row;

    --procedure보다는 function이 더 직관적이므로
--    procedure get_perf(l_out out nocopy t_tf_row);
    function get_perf(v_sid in number) return t_tf_row;
    function get_delta(after in t_tf_row, before in t_tf_row) return t_tf_row;

    function get(p_sid in number, p_rows in number, p_interval in number) return t_tf_tab pipelined;
end pinetri;